name: Test Workflow
on:
  push:
    branches: [ "main", "lab_solution" ]
  pull_request:
    branches: [ "main", "lab_solution" ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install flask pytest
      - name: Run unit tests
        run: |
          source venv/bin/activate
          python -m pytest test_hello_world.py -v